const router = require('express').Router()

const auth = require('~/routes/auth')
const user = require('~/routes/user')
const email = require('~/routes/email')
const location = require('~/routes/location')
const adminInvitation = require('~/routes/adminInvitation')
const lesson = require('~/routes/lesson')
const chat = require('~/routes/chat')
const message = require('~/routes/message')
const quiz = require('~/routes/quiz')
const attachment = require('~/routes/attachment')
const finishedQuiz = require('~/routes/finishedQuiz')
const question = require('~/routes/question')
const resourcesCategory = require('~/routes/resourcesCategory')

router.use('/auth', auth)
router.use('/users', user)
router.use('/send-email', email)
router.use('/location', location)
router.use('/admin-invitations', adminInvitation)
router.use('/lessons', lesson)
router.use('/chats', chat)
router.use('/messages', message)
router.use('/quizzes', quiz)
router.use('/attachments', attachment)
router.use('/finished-quizzes', finishedQuiz)
router.use('/questions', question)
router.use('/resources-categories', resourcesCategory)

module.exports = router
